// AUTO-GENERATED — DO NOT EDIT.
// Source of truth: the routers under apps/api/alppy/api/v1/, as
// FastAPI collects them (create_app().openapi()).
// Regenerate with: PYTHONPATH=apps/api python scripts/generate-api-types.py

/** Every `METHOD /path` this API serves. */
export const API_ROUTES = [
  'DELETE /api/v1/chapters/{chapter_id}',
  'DELETE /api/v1/classes/{class_id}/students/{student_id}/enrollment',
  'DELETE /api/v1/classes/{class_id}/subjects/{subject_id}',
  'DELETE /api/v1/classes/{class_id}/teachers/{teacher_id}/branches/{subject_id}',
  'DELETE /api/v1/sources/{source_id}',
  'DELETE /api/v1/students/{student_id}',
  'GET /api/v1/adaptive/feedback',
  'GET /api/v1/adaptive/proposal/{job_id}',
  'GET /api/v1/auth/me',
  'GET /api/v1/chapters',
  'GET /api/v1/classes',
  'GET /api/v1/classes/{class_id}',
  'GET /api/v1/classes/{class_id}/mastery',
  'GET /api/v1/classes/{class_id}/points',
  'GET /api/v1/classes/{class_id}/students',
  'GET /api/v1/classes/{class_id}/teachers',
  'GET /api/v1/classes/{class_id}/tree',
  'GET /api/v1/colleagues',
  'GET /api/v1/curricula/{kind}/competencies',
  'GET /api/v1/files/{key}',
  'GET /api/v1/health',
  'GET /api/v1/home',
  'GET /api/v1/jobs',
  'GET /api/v1/jobs/{job_id}',
  'GET /api/v1/scans',
  'GET /api/v1/scans/{scan_id}',
  'GET /api/v1/scans/{scan_id}/detections',
  'GET /api/v1/scans/{scan_id}/students',
  'GET /api/v1/school-years',
  'GET /api/v1/sheets',
  'GET /api/v1/sheets/{sheet_id}',
  'GET /api/v1/sheets/{sheet_id}/confidence',
  'GET /api/v1/sheets/{sheet_id}/mastery',
  'GET /api/v1/sheets/{sheet_id}/preview',
  'GET /api/v1/sources',
  'GET /api/v1/sources/{source_id}',
  'GET /api/v1/sources/{source_id}/exercises',
  'GET /api/v1/sources/{source_id}/sections',
  'GET /api/v1/sources/{source_id}/status',
  'GET /api/v1/students/{student_id}/competencies/{competency_id}/attempts',
  'GET /api/v1/students/{student_id}/mastery',
  'GET /api/v1/students/{student_id}/sheets/{sheet_id}',
  'GET /api/v1/subjects',
  'GET /api/v1/timeline',
  'PATCH /api/v1/chapters/{chapter_id}',
  'PATCH /api/v1/classes/{class_id}',
  'PATCH /api/v1/exercises/{exercise_id}',
  'PATCH /api/v1/scans/{scan_id}/detections/{detection_id}',
  'PATCH /api/v1/scans/{scan_id}/pages/{page_id}',
  'PATCH /api/v1/schools/me',
  'PATCH /api/v1/sheets/{sheet_id}',
  'PATCH /api/v1/sources/{source_id}',
  'PATCH /api/v1/students/{student_id}',
  'PATCH /api/v1/subjects/{subject_id}',
  'PATCH /api/v1/teachers/me/preferences',
  'POST /api/v1/adaptive/approve',
  'POST /api/v1/adaptive/batch',
  'POST /api/v1/adaptive/batch/{sheet_id}/render',
  'POST /api/v1/adaptive/discard',
  'POST /api/v1/adaptive/feedback/approve',
  'POST /api/v1/adaptive/feedback/discard',
  'POST /api/v1/adaptive/feedback/generate',
  'POST /api/v1/adaptive/propose',
  'POST /api/v1/adaptive/regenerate',
  'POST /api/v1/auth/login',
  'POST /api/v1/auth/logout',
  'POST /api/v1/auth/school/{school_id}',
  'POST /api/v1/chapters',
  'POST /api/v1/classes',
  'POST /api/v1/classes/{class_id}/students',
  'POST /api/v1/classes/{class_id}/students/{student_id}/enrollment',
  'POST /api/v1/classes/{class_id}/subjects/{subject_id}',
  'POST /api/v1/classes/{class_id}/teachers/{teacher_id}/branches/{subject_id}',
  'POST /api/v1/exercises',
  'POST /api/v1/scans',
  'POST /api/v1/scans/{scan_id}/confirm',
  'POST /api/v1/scans/{scan_id}/detections/{detection_id}/revert',
  'POST /api/v1/scans/{scan_id}/pages/{page_id}/discard',
  'POST /api/v1/scans/{scan_id}/reopen',
  'POST /api/v1/schools',
  'POST /api/v1/schools/{school_id}/teachers/{teacher_id}',
  'POST /api/v1/sheets',
  'POST /api/v1/sheets/preview',
  'POST /api/v1/sheets/propose',
  'POST /api/v1/sheets/{sheet_id}/printed',
  'POST /api/v1/sheets/{sheet_id}/render',
  'POST /api/v1/sources',
  'POST /api/v1/sources/{source_id}/sections/{section_id}/extract',
  'POST /api/v1/subjects',
  'PUT /api/v1/classes/{class_id}/subjects',
] as const;

export type ApiRoute = (typeof API_ROUTES)[number];
