// AUTO-GENERATED — DO NOT EDIT.
// Source of truth: the routers under apps/api/alppy/api/v1/, as
// FastAPI collects them (create_app().openapi()).
// Regenerate with: PYTHONPATH=apps/api python scripts/generate-api-types.py

/** Every `METHOD /path` this API serves. */
export const API_ROUTES = [
  'DELETE /api/v1/chapters/{chapter_id}',
  'DELETE /api/v1/classes/{class_id}/students/{student_id}/enrollment',
  'DELETE /api/v1/classes/{class_id}/subjects/{subject_id}',
  'DELETE /api/v1/classes/{class_id}/teachers/{teacher_id}/branches/{subject_id}',
  'DELETE /api/v1/sources/{source_id}',
  'DELETE /api/v1/students/{student_id}',
  'GET /api/v1/adaptive/feedback',
  'GET /api/v1/adaptive/proposal/{job_id}',
  'GET /api/v1/auth/me',
  'GET /api/v1/chapters',
  'GET /api/v1/classes',
  'GET /api/v1/classes/{class_id}',
  'GET /api/v1/classes/{class_id}/mastery',
  'GET /api/v1/classes/{class_id}/points',
  'GET /api/v1/classes/{class_id}/students',
  'GET /api/v1/classes/{class_id}/teachers',
  'GET /api/v1/classes/{class_id}/tree',
  'GET /api/v1/colleagues',
  'GET /api/v1/curricula/{kind}/competencies',
  'GET /api/v1/exercises',
  'GET /api/v1/files/{key}',
  'GET /api/v1/health',
  'GET /api/v1/home',
  'GET /api/v1/jobs',
  'GET /api/v1/jobs/{job_id}',
  'GET /api/v1/scans',
  'GET /api/v1/scans/{scan_id}',
  'GET /api/v1/scans/{scan_id}/detections',
  'GET /api/v1/scans/{scan_id}/students',
  'GET /api/v1/school-years',
  'GET /api/v1/sheets',
  'GET /api/v1/sheets/{sheet_id}',
  'GET /api/v1/sheets/{sheet_id}/confidence',
  'GET /api/v1/sheets/{sheet_id}/mastery',
  'GET /api/v1/sheets/{sheet_id}/preview',
  'GET /api/v1/sources',
  'GET /api/v1/sources/{source_id}',
  'GET /api/v1/sources/{source_id}/exercises',
  'GET /api/v1/sources/{source_id}/sections',
  'GET /api/v1/sources/{source_id}/status',
  'GET /api/v1/students/{student_id}/competencies/{competency_id}/attempts',
  'GET /api/v1/students/{student_id}/export',
  'GET /api/v1/students/{student_id}/mastery',
  'GET /api/v1/students/{student_id}/sheets/{sheet_id}',
  'GET /api/v1/subjects',
  'GET /api/v1/timeline',
  'PATCH /api/v1/chapters/{chapter_id}',
  'PATCH /api/v1/classes/{class_id}',
  'PATCH /api/v1/exercises/{exercise_id}',
  'PATCH /api/v1/scans/{scan_id}/detections/{detection_id}',
  'PATCH /api/v1/scans/{scan_id}/pages/{page_id}',
  'PATCH /api/v1/schools/me',
  'PATCH /api/v1/sheets/{sheet_id}',
  'PATCH /api/v1/sources/{source_id}',
  'PATCH /api/v1/students/{student_id}',
  'PATCH /api/v1/subjects/{subject_id}',
  'PATCH /api/v1/teachers/me/preferences',
  'POST /api/v1/adaptive/approve',
  'POST /api/v1/adaptive/batch',
  'POST /api/v1/adaptive/batch/{sheet_id}/render',
  'POST /api/v1/adaptive/discard',
  'POST /api/v1/adaptive/feedback/approve',
  'POST /api/v1/adaptive/feedback/discard',
  'POST /api/v1/adaptive/feedback/generate',
  'POST /api/v1/adaptive/propose',
  'POST /api/v1/adaptive/regenerate',
  'POST /api/v1/auth/login',
  'POST /api/v1/auth/logout',
  'POST /api/v1/auth/school/{school_id}',
  'POST /api/v1/chapters',
  'POST /api/v1/classes',
  'POST /api/v1/classes/{class_id}/students',
  'POST /api/v1/classes/{class_id}/students/{student_id}/enrollment',
  'POST /api/v1/classes/{class_id}/subjects/{subject_id}',
  'POST /api/v1/classes/{class_id}/teachers/{teacher_id}/branches/{subject_id}',
  'POST /api/v1/exercises',
  'POST /api/v1/scans',
  'POST /api/v1/scans/{scan_id}/confirm',
  'POST /api/v1/scans/{scan_id}/detections/{detection_id}/revert',
  'POST /api/v1/scans/{scan_id}/pages/{page_id}/discard',
  'POST /api/v1/scans/{scan_id}/reopen',
  'POST /api/v1/schools',
  'POST /api/v1/schools/{school_id}/teachers/{teacher_id}',
  'POST /api/v1/sheets',
  'POST /api/v1/sheets/preview',
  'POST /api/v1/sheets/propose',
  'POST /api/v1/sheets/{sheet_id}/printed',
  'POST /api/v1/sheets/{sheet_id}/render',
  'POST /api/v1/sources',
  'POST /api/v1/sources/{source_id}/sections/{section_id}/extract',
  'POST /api/v1/students/{student_id}/anonymise',
  'POST /api/v1/subjects',
  'PUT /api/v1/classes/{class_id}/subjects',
] as const;

export type ApiRoute = (typeof API_ROUTES)[number];

/**
 * What each route RETURNS, as the TypeScript type expression for it.
 *
 * `apiRequest<T>` is an assertion and not a check: the client states the
 * shape it expects and TypeScript believes it, so a route whose response
 * model changes goes on compiling at every call site while the data
 * underneath is a different shape. The generated types cannot see that —
 * they describe the document, not who reads it. This is the join, and
 * `contract.test.ts` is what enforces it.
 */
export const API_RESPONSES: Record<string, string> = {
  'DELETE /api/v1/chapters/{chapter_id}': 'void',
  'DELETE /api/v1/classes/{class_id}/students/{student_id}/enrollment': 'StudentOut[]',
  'DELETE /api/v1/classes/{class_id}/subjects/{subject_id}': 'ClassOut',
  'DELETE /api/v1/classes/{class_id}/teachers/{teacher_id}/branches/{subject_id}': 'ClassTeacherOut[]',
  'DELETE /api/v1/sources/{source_id}': 'void',
  'DELETE /api/v1/students/{student_id}': 'void',
  'GET /api/v1/adaptive/feedback': 'MisconceptionNoteOut[]',
  'GET /api/v1/adaptive/proposal/{job_id}': 'AdaptiveProposeResponse',
  'GET /api/v1/auth/me': 'TeacherOut',
  'GET /api/v1/chapters': 'ChapterOut[]',
  'GET /api/v1/classes': 'ClassOut[]',
  'GET /api/v1/classes/{class_id}': 'ClassOut',
  'GET /api/v1/classes/{class_id}/mastery': 'MasteryMatrixOut',
  'GET /api/v1/classes/{class_id}/points': 'ClassPointsOut',
  'GET /api/v1/classes/{class_id}/students': 'StudentOut[]',
  'GET /api/v1/classes/{class_id}/teachers': 'ClassTeacherOut[]',
  'GET /api/v1/classes/{class_id}/tree': 'ClassTreeOut',
  'GET /api/v1/colleagues': 'ColleagueOut[]',
  'GET /api/v1/curricula/{kind}/competencies': 'CompetencyListOut',
  'GET /api/v1/exercises': 'ExerciseListOut',
  'GET /api/v1/files/{key}': 'void',
  'GET /api/v1/health': 'HealthOut',
  'GET /api/v1/home': 'HomeOut',
  'GET /api/v1/jobs': 'JobOut[]',
  'GET /api/v1/jobs/{job_id}': 'JobOut',
  'GET /api/v1/scans': 'ScanOut[]',
  'GET /api/v1/scans/{scan_id}': 'ScanOut',
  'GET /api/v1/scans/{scan_id}/detections': 'DetectionListOut',
  'GET /api/v1/scans/{scan_id}/students': 'StudentOut[]',
  'GET /api/v1/school-years': 'SchoolYearOut[]',
  'GET /api/v1/sheets': 'SheetOut[]',
  'GET /api/v1/sheets/{sheet_id}': 'SheetOut',
  'GET /api/v1/sheets/{sheet_id}/confidence': 'SheetConfidenceOut',
  'GET /api/v1/sheets/{sheet_id}/mastery': 'SheetMasteryOut',
  'GET /api/v1/sheets/{sheet_id}/preview': 'string',
  'GET /api/v1/sources': 'SourceOut[]',
  'GET /api/v1/sources/{source_id}': 'SourceOut',
  'GET /api/v1/sources/{source_id}/exercises': 'ExerciseListOut',
  'GET /api/v1/sources/{source_id}/sections': 'SourceSectionOut[]',
  'GET /api/v1/sources/{source_id}/status': 'JobOut',
  'GET /api/v1/students/{student_id}/competencies/{competency_id}/attempts': 'CompetencyAttemptsOut',
  'GET /api/v1/students/{student_id}/export': 'StudentExportOut',
  'GET /api/v1/students/{student_id}/mastery': 'StudentProfileOut',
  'GET /api/v1/students/{student_id}/sheets/{sheet_id}': 'StudentSheetOut',
  'GET /api/v1/subjects': 'SubjectOut[]',
  'GET /api/v1/timeline': 'TimelineOut',
  'PATCH /api/v1/chapters/{chapter_id}': 'ChapterOut',
  'PATCH /api/v1/classes/{class_id}': 'ClassOut',
  'PATCH /api/v1/exercises/{exercise_id}': 'ExerciseOut',
  'PATCH /api/v1/scans/{scan_id}/detections/{detection_id}': 'DetectionOut',
  'PATCH /api/v1/scans/{scan_id}/pages/{page_id}': 'ScanPageOut',
  'PATCH /api/v1/schools/me': 'SchoolOut',
  'PATCH /api/v1/sheets/{sheet_id}': 'SheetOut',
  'PATCH /api/v1/sources/{source_id}': 'SourceOut',
  'PATCH /api/v1/students/{student_id}': 'StudentOut',
  'PATCH /api/v1/subjects/{subject_id}': 'SubjectOut',
  'PATCH /api/v1/teachers/me/preferences': 'TeacherOut',
  'POST /api/v1/adaptive/approve': 'AdaptiveApproveResponse',
  'POST /api/v1/adaptive/batch': 'SheetOut',
  'POST /api/v1/adaptive/batch/{sheet_id}/render': 'JobOut',
  'POST /api/v1/adaptive/discard': 'AdaptiveDiscardResponse',
  'POST /api/v1/adaptive/feedback/approve': 'FeedbackApproveResponse',
  'POST /api/v1/adaptive/feedback/discard': 'FeedbackDiscardResponse',
  'POST /api/v1/adaptive/feedback/generate': 'JobOut',
  'POST /api/v1/adaptive/propose': 'JobOut',
  'POST /api/v1/adaptive/regenerate': 'AdaptiveRegenerateResponse',
  'POST /api/v1/auth/login': 'TeacherOut',
  'POST /api/v1/auth/logout': 'void',
  'POST /api/v1/auth/school/{school_id}': 'TeacherOut',
  'POST /api/v1/chapters': 'ChapterOut',
  'POST /api/v1/classes': 'ClassOut',
  'POST /api/v1/classes/{class_id}/students': 'StudentOut[]',
  'POST /api/v1/classes/{class_id}/students/{student_id}/enrollment': 'StudentOut[]',
  'POST /api/v1/classes/{class_id}/subjects/{subject_id}': 'ClassOut',
  'POST /api/v1/classes/{class_id}/teachers/{teacher_id}/branches/{subject_id}': 'ClassTeacherOut[]',
  'POST /api/v1/exercises': 'ExerciseOut',
  'POST /api/v1/scans': 'ScanOut',
  'POST /api/v1/scans/{scan_id}/confirm': 'ScanConfirmResponse',
  'POST /api/v1/scans/{scan_id}/detections/{detection_id}/revert': 'DetectionOut',
  'POST /api/v1/scans/{scan_id}/pages/{page_id}/discard': 'ScanPageOut',
  'POST /api/v1/scans/{scan_id}/reopen': 'ScanUnvalidateResponse',
  'POST /api/v1/schools': 'SchoolOut',
  'POST /api/v1/schools/{school_id}/teachers/{teacher_id}': 'ColleagueOut[]',
  'POST /api/v1/sheets': 'SheetOut',
  'POST /api/v1/sheets/preview': 'string',
  'POST /api/v1/sheets/propose': 'SheetProposeResponse',
  'POST /api/v1/sheets/{sheet_id}/printed': 'SheetOut',
  'POST /api/v1/sheets/{sheet_id}/render': 'JobOut',
  'POST /api/v1/sources': 'SourceOut',
  'POST /api/v1/sources/{source_id}/sections/{section_id}/extract': 'JobOut',
  'POST /api/v1/students/{student_id}/anonymise': 'StudentOut',
  'POST /api/v1/subjects': 'SubjectOut',
  'PUT /api/v1/classes/{class_id}/subjects': 'ClassOut',
};
