#!/usr/bin/env node
/**
 * Embed the design system's type into a stylesheet the printed sheet can carry.
 *
 * `packages/ui/src/design/tokens.css` NAMES four families — Fredoka, Nunito,
 * JetBrains Mono, Caveat — and until this script existed, nothing outside the
 * Next bundle ever loaded them. The web app imports the `@fontsource-variable`
 * packages from its own layout, which is a JavaScript import that ends up in
 * the web bundle's CSS; the print document is served by the API, has no bundle,
 * and so resolved `--font-sans` to whatever each renderer fell back to:
 * Liberation/DejaVu in the API's headless Chromium, SF Pro or Segoe UI in the
 * teacher's browser, and something else again in the browser's print dialog.
 *
 * That is not only an identity problem. `measure_answer_boxes` asks Chromium
 * where each answer box landed *in that Chromium, with those metrics*, and the
 * scan job crops at exactly those millimetres. A statement that wraps to four
 * lines in DejaVu and three in SF Pro moves its box by one line pitch (8 mm) —
 * far enough to crop the wrong pixels, not far enough for
 * `_check_box_inside_statement_region` to raise. So the three renderers have to
 * agree on the type, and the only way to guarantee that for a standalone
 * document is to carry the faces inside it.
 *
 * The output is committed. The API's container image has no `node_modules`
 * (`apps/api/Dockerfile` copies `packages/ui/src/design/` and nothing else from
 * the workspace), so the generated file — not the packages — is what ships.
 *
 * Latin only: the sheets are French, German and English. `U+0152-0153` (Œ œ)
 * and the umlauts are both inside the `latin` subset, so nothing a French or
 * German worksheet prints falls out of it. Normal only: the print templates run
 * under `autoescape=True`, so no statement can carry `<em>` and no italic face
 * can ever be asked for.
 *
 * Usage:
 *     node scripts/embed-fonts.mjs
 *
 * Re-run it when a font package is upgraded; CI re-runs it and fails if the
 * committed file changes, the same way `export-layout.py` guards the geometry.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT_PATH = join(REPO_ROOT, 'packages', 'ui', 'src', 'design', 'fonts.css');

/**
 * The packages behind the four families, in the order `tokens.css` declares
 * them. The family name is not written here — it is read out of the package's
 * own `index.css`, so a package that renames its face cannot leave this script
 * emitting a face nothing references.
 */
const PACKAGES = ['fredoka', 'nunito', 'jetbrains-mono', 'caveat'];

/** The one subset we ship, and the one style. See the module docstring. */
const SUBSET = 'latin';
const STYLE = 'normal';

function packageDir(name) {
  const candidates = [
    join(REPO_ROOT, 'apps', 'web', 'node_modules', '@fontsource-variable', name),
    join(REPO_ROOT, 'node_modules', '@fontsource-variable', name),
  ];
  const found = candidates.find((dir) => existsSync(join(dir, 'index.css')));
  if (!found) {
    throw new Error(
      `@fontsource-variable/${name} not found — run pnpm install first (looked in ${candidates.join(', ')})`,
    );
  }
  return found;
}

/**
 * The `@font-face` block for one subset, read out of the package rather than
 * retyped. We keep the package's own `font-family`, `font-weight` range and
 * `unicode-range`: those are facts about the file, and a hand-copied weight
 * range is how a variable font silently becomes a single weight.
 */
function faceFor(pkg) {
  const dir = packageDir(pkg);
  const index = readFileSync(join(dir, 'index.css'), 'utf8');
  const fileName = `${pkg}-${SUBSET}-wght-${STYLE === 'normal' ? 'normal' : STYLE}.woff2`;

  const block = index
    .split('@font-face')
    .slice(1)
    .map((chunk) => chunk.slice(chunk.indexOf('{') + 1, chunk.indexOf('}')))
    .find((body) => body.includes(fileName));
  if (!block) {
    throw new Error(`no @font-face for ${fileName} in @fontsource-variable/${pkg}/index.css`);
  }

  const field = (name) => {
    const match = block.match(new RegExp(`${name}\\s*:\\s*([^;]+);`));
    if (!match) throw new Error(`${pkg}: no ${name} in the ${SUBSET} face`);
    return match[1].trim();
  };

  const woff2 = readFileSync(join(dir, 'files', fileName));
  return {
    pkg,
    fileName,
    bytes: woff2.length,
    family: field('font-family'),
    weight: field('font-weight'),
    unicodeRange: field('unicode-range'),
    data: woff2.toString('base64'),
  };
}

const faces = PACKAGES.map(faceFor);

const header = `/*
 * GENERATED by scripts/embed-fonts.mjs — do not edit.
 *
 * The four families tokens.css names, carried as data: URIs so a standalone
 * print document typesets in the design system's own type rather than in
 * whatever each renderer falls back to. The PDF, the preview iframe and a
 * browser print of that preview all read this same block, which is what makes
 * the measured position of an answer box true of the paper it was measured
 * from. See the script for why that is a grading concern and not a taste one.
 *
 * Latin subset, normal style only. Regenerate with:
 *     node scripts/embed-fonts.mjs
 *
 * font-display: block — paper has no "swap". A page that laid out in a
 * fallback and then reflowed would be a page whose answer boxes moved.
 */
`;

const css =
  header +
  faces
    .map(
      (face) => `
/* @fontsource-variable/${face.pkg} · ${face.fileName} · ${face.bytes} bytes */
@font-face {
  font-family: ${face.family};
  font-style: ${STYLE};
  font-display: block;
  font-weight: ${face.weight};
  src: url(data:font/woff2;base64,${face.data}) format('woff2-variations');
  unicode-range: ${face.unicodeRange};
}
`,
    )
    .join('');

writeFileSync(OUTPUT_PATH, css, 'utf8');

const total = faces.reduce((sum, face) => sum + face.bytes, 0);
process.stdout.write(
  `${OUTPUT_PATH.replace(`${REPO_ROOT}/`, '')}: ${faces.length} faces, ` +
    `${(total / 1024).toFixed(0)} KiB of woff2, ${(css.length / 1024).toFixed(0)} KiB of CSS\n`,
);
for (const face of faces) {
  process.stdout.write(`  ${face.family} — ${(face.bytes / 1024).toFixed(0)} KiB\n`);
}
