"""Initial schema — every table in alppy.models.

Hand-written (not autogenerated against a live database, since none is
available while this migration was authored) but every column, type,
nullability, foreign key, unique/check constraint and index below was
generated directly from ``alppy.models.Base.metadata`` — the same metadata
SQLAlchemy uses for the ORM — and then read back table-by-table against
``apps/api/alppy/models/__init__.py`` and ``apps/api/alppy/db/base.py``. See
the constraint-naming convention in ``alppy.db.base.NAMING_CONVENTION``: every
constraint name below (``pk_*``, ``fk_*_*_*``, ``uq_*_*``, ``ck_*_*``, and the
default-labelled ``ix_*``) is exactly what that convention produces, so a
future ``alembic revision --autogenerate`` diffs cleanly against this
baseline instead of proposing to rename everything.

Tables are created in dependency order (every foreign key points at a table
already created, or — for ``competency.parent_id`` — at itself, which
PostgreSQL allows inline). Enum types are created explicitly with
``CREATE TYPE ... AS ENUM`` before any column references them, since two
tables can share one enum (``job_status`` is used by both ``source`` and
``job``) and a bare ``sa.Enum(...)`` on the second occurrence would otherwise
try to recreate it — hence ``create_type=False`` on every enum column
below.

Revision ID: 0001
Revises:
Create Date: 2026-09-05
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

# --------------------------------------------------------------------------
# Enum types, in first-use order. Values are the Python Enum *member names*
# (e.g. "FR", not "fr") because SQLAlchemy's ``Enum`` type stores
# ``member.name`` by default -- see alppy.models.enums for the Python side.
# --------------------------------------------------------------------------
_ENUMS: dict[str, list[str]] = {
    "curriculum_kind": ["LP21", "PER"],
    "locale": ["FR", "DE", "EN"],
    "job_status": ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED"],
    "exercise_type": ["MCQ", "TRUE_FALSE", "OPEN"],
    "exercise_origin": ["TEXTBOOK", "AI_GENERATED"],
    "sheet_target": ["CLASS", "STUDENT", "GROUP"],
    "scan_status": ["UPLOADED", "PROCESSING", "NEEDS_REVIEW", "CONFIRMED", "FAILED"],
    "detection_outcome": [
        "DETECTED",
        "LOW_CONFIDENCE",
        "BLANK",
        "MULTIPLE",
        "CORRECTED",
        "NOT_GRADEABLE",
    ],
    "mastery_band": ["SOLID", "OK", "WEAK", "FADING", "NONE"],
    "job_kind": ["INGEST_SOURCE", "RENDER_SHEET", "PROCESS_SCAN", "GENERATE_ADAPTIVE"],
}

# Tables in FK-dependency order (every referenced table -- or, for
# competency's self-referential parent_id, itself -- is created first).
_TABLE_DROP_ORDER = [
    "job",
    "model_call",
    "mastery_snapshot",
    "attempt",
    "detection",
    "scan_page",
    "scan",
    "sheet_instance",
    "sheet_item",
    "sheet",
    "exercise_variant",
    "exercise_competency",
    "exercise",
    "source_chunk",
    "source",
    "chapter_competency",
    "chapter",
    "competency",
    "student",
    "class",
    "subject",
    "school_year",
    "teacher",
    "school",
]


def upgrade() -> None:
    # pgvector for SourceChunk.embedding (vector(1024) -- see
    # alppy.core.config.Settings.embedding_dim).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    for name, values in _ENUMS.items():
        values_sql = ", ".join(f"'{v}'" for v in values)
        op.execute(f"CREATE TYPE {name} AS ENUM ({values_sql})")

    op.create_table(
        "school",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("canton", sa.String(length=2), nullable=True),
        sa.Column(
            "default_curriculum",
            postgresql.ENUM("LP21", "PER", name="curriculum_kind", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name="pk_school"),
    )

    op.create_table(
        "teacher",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "locale",
            postgresql.ENUM("FR", "DE", "EN", name="locale", create_type=False),
            nullable=False,
        ),
        sa.Column("theme", sa.String(length=10), nullable=True),
        sa.Column("contrast", sa.String(length=10), nullable=True),
        sa.Column("motion", sa.String(length=10), nullable=True),
        sa.Column("calm", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_teacher"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_teacher_school_id_school", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("email", name="uq_teacher_email"),
    )
    op.create_index("ix_teacher_email", "teacher", ["email"])
    op.create_index("ix_teacher_school_id", "teacher", ["school_id"])

    op.create_table(
        "school_year",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_school_year"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_school_year_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_school_year_school_id", "school_year", ["school_id"])

    op.create_table(
        "subject",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_subject"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_subject_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_subject_school_id", "subject", ["school_id"])

    op.create_table(
        "class",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("school_year_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("teacher_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_class"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_class_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["school_year_id"],
            ["school_year.id"],
            name="fk_class_school_year_id_school_year",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teacher.id"], name="fk_class_teacher_id_teacher", ondelete="RESTRICT"
        ),
        sa.UniqueConstraint("school_id", "school_year_id", "code", name="uq_class_code"),
    )
    op.create_index("ix_class_teacher_id", "class", ["teacher_id"])
    op.create_index("ix_class_school_year_id", "class", ["school_year_id"])
    op.create_index("ix_class_school_id", "class", ["school_id"])

    op.create_table(
        "student",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("class_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("school_year_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("uid", sa.String(length=20), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_student"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_student_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["school_year_id"],
            ["school_year.id"],
            name="fk_student_school_year_id_school_year",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"], ["class.id"], name="fk_student_class_id_class", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("school_id", "school_year_id", "uid", name="uq_student_uid"),
        sa.CheckConstraint("number > 0", name="ck_student_number_positive"),
    )
    op.create_index("ix_student_school_year_id", "student", ["school_year_id"])
    op.create_index("ix_student_uid", "student", ["uid"])
    op.create_index("ix_student_school_id", "student", ["school_id"])
    op.create_index("ix_student_class_id", "student", ["class_id"])

    op.create_table(
        "competency",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "curriculum",
            postgresql.ENUM("LP21", "PER", name="curriculum_kind", create_type=False),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("subject_key", sa.String(length=50), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name="pk_competency"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["competency.id"],
            name="fk_competency_parent_id_competency",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint("curriculum", "code", name="uq_competency_code"),
    )
    op.create_index("ix_competency_subject_cycle", "competency", ["subject_key", "cycle"])

    op.create_table(
        "chapter",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_chapter"),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subject.id"], name="fk_chapter_subject_id_subject", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_chapter_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_chapter_subject_id", "chapter", ["subject_id"])
    op.create_index("ix_chapter_school_id", "chapter", ["school_id"])

    op.create_table(
        "chapter_competency",
        sa.Column("chapter_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("competency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("chapter_id", "competency_id", name="pk_chapter_competency"),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name="fk_chapter_competency_chapter_id_chapter",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency.id"],
            name="fk_chapter_competency_competency_id_competency",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "source",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("uploaded_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED", "RUNNING", "SUCCEEDED", "FAILED", name="job_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_source"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_source_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["teacher.id"],
            name="fk_source_uploaded_by_id_teacher",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subject.id"], name="fk_source_subject_id_subject", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_source_school_id", "source", ["school_id"])
    op.create_index("ix_source_sha256", "source", ["sha256"])
    op.create_index("ix_source_uploaded_by_id", "source", ["uploaded_by_id"])
    op.create_index("ix_source_subject_id", "source", ["subject_id"])

    op.create_table(
        "source_chunk",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_source_chunk"),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name="fk_source_chunk_school_id_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name="fk_source_chunk_source_id_source",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_source_chunk_school_id", "source_chunk", ["school_id"])
    op.create_index("ix_source_chunk_source_page", "source_chunk", ["source_id", "page"])
    op.create_index("ix_source_chunk_source_id", "source_chunk", ["source_id"])

    op.create_table(
        "exercise",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chapter_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_chunk_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM("MCQ", "TRUE_FALSE", "OPEN", name="exercise_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "origin",
            postgresql.ENUM("TEXTBOOK", "AI_GENERATED", name="exercise_origin", create_type=False),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_index", sa.Integer(), nullable=True),
        sa.Column("answer_bool", sa.Boolean(), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generation_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_exercise"),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["source_chunk.id"],
            name="fk_exercise_source_chunk_id_source_chunk",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name="fk_exercise_source_id_source", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_exercise_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
            name="fk_exercise_subject_id_subject",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name="fk_exercise_chapter_id_chapter",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 5", name="ck_exercise_difficulty_range"),
    )
    op.create_index("ix_exercise_school_id", "exercise", ["school_id"])
    op.create_index("ix_exercise_source_chunk_id", "exercise", ["source_chunk_id"])
    op.create_index("ix_exercise_chapter_id", "exercise", ["chapter_id"])
    op.create_index("ix_exercise_source_id", "exercise", ["source_id"])
    op.create_index("ix_exercise_subject_origin", "exercise", ["subject_id", "origin"])
    op.create_index("ix_exercise_subject_id", "exercise", ["subject_id"])

    op.create_table(
        "exercise_competency",
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("competency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("exercise_id", "competency_id", name="pk_exercise_competency"),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
            name="fk_exercise_competency_exercise_id_exercise",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency.id"],
            name="fk_exercise_competency_competency_id_competency",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "exercise_variant",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_index", sa.Integer(), nullable=True),
        sa.Column("answer_bool", sa.Boolean(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("generation_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_exercise_variant"),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_exercise_variant_student_id_student",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name="fk_exercise_variant_school_id_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
            name="fk_exercise_variant_exercise_id_exercise",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_exercise_variant_exercise_id", "exercise_variant", ["exercise_id"])
    op.create_index("ix_exercise_variant_student_id", "exercise_variant", ["student_id"])
    op.create_index("ix_exercise_variant_school_id", "exercise_variant", ["school_id"])

    op.create_table(
        "sheet",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("class_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "target",
            postgresql.ENUM("CLASS", "STUDENT", "GROUP", name="sheet_target", create_type=False),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("intent", sa.Text(), nullable=True),
        sa.Column("layout_version", sa.String(length=10), nullable=False),
        sa.Column("blank_pdf_key", sa.String(length=500), nullable=True),
        sa.Column("answer_key_pdf_key", sa.String(length=500), nullable=True),
        sa.Column("rendered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_sheet"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_sheet_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subject.id"], name="fk_sheet_subject_id_subject", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["teacher.id"],
            name="fk_sheet_created_by_id_teacher",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"], ["class.id"], name="fk_sheet_class_id_class", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_sheet_subject_id", "sheet", ["subject_id"])
    op.create_index("ix_sheet_school_id", "sheet", ["school_id"])
    op.create_index("ix_sheet_created_by_id", "sheet", ["created_by_id"])
    op.create_index("ix_sheet_class_id", "sheet", ["class_id"])

    op.create_table(
        "sheet_item",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sheet_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("statement_override", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_sheet_item"),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["sheet.id"], name="fk_sheet_item_sheet_id_sheet", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_sheet_item_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
            name="fk_sheet_item_exercise_id_exercise",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("sheet_id", "position", name="uq_sheet_item_position"),
    )
    op.create_index("ix_sheet_item_exercise_id", "sheet_item", ["exercise_id"])
    op.create_index("ix_sheet_item_sheet_id", "sheet_item", ["sheet_id"])
    op.create_index("ix_sheet_item_school_id", "sheet_item", ["school_id"])

    op.create_table(
        "sheet_instance",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sheet_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_uid", sa.String(length=20), nullable=False),
        sa.Column("item_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_sheet_instance"),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["sheet.id"], name="fk_sheet_instance_sheet_id_sheet", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_sheet_instance_student_id_student",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name="fk_sheet_instance_school_id_school",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("sheet_id", "student_id", name="uq_instance_student"),
    )
    op.create_index("ix_sheet_instance_student_id", "sheet_instance", ["student_id"])
    op.create_index("ix_sheet_instance_student_uid", "sheet_instance", ["student_uid"])
    op.create_index("ix_sheet_instance_school_id", "sheet_instance", ["school_id"])
    op.create_index("ix_sheet_instance_sheet_id", "sheet_instance", ["sheet_id"])

    op.create_table(
        "scan",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sheet_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("uploaded_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "UPLOADED",
                "PROCESSING",
                "NEEDS_REVIEW",
                "CONFIRMED",
                "FAILED",
                name="scan_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scan"),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["sheet.id"], name="fk_scan_sheet_id_sheet", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["teacher.id"],
            name="fk_scan_uploaded_by_id_teacher",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_scan_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_scan_uploaded_by_id", "scan", ["uploaded_by_id"])
    op.create_index("ix_scan_school_id", "scan", ["school_id"])
    op.create_index("ix_scan_sheet_id", "scan", ["sheet_id"])

    op.create_table(
        "scan_page",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("scan_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page_index", sa.Integer(), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=False),
        sa.Column("registered", sa.Boolean(), nullable=False),
        sa.Column("registration_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detected_uid", sa.String(length=20), nullable=True),
        sa.Column("uid_confidence", sa.Float(), nullable=True),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sheet_instance_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scan_page"),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scan.id"], name="fk_scan_page_scan_id_scan", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sheet_instance_id"],
            ["sheet_instance.id"],
            name="fk_scan_page_sheet_instance_id_sheet_instance",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_scan_page_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_scan_page_student_id_student",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_scan_page_school_id", "scan_page", ["school_id"])
    op.create_index("ix_scan_page_student_id", "scan_page", ["student_id"])
    op.create_index("ix_scan_page_sheet_instance_id", "scan_page", ["sheet_instance_id"])
    op.create_index("ix_scan_page_scan_id", "scan_page", ["scan_id"])
    op.create_index("ix_scan_page_detected_uid", "scan_page", ["detected_uid"])

    op.create_table(
        "detection",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("scan_page_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sheet_item_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("item_index", sa.Integer(), nullable=False),
        sa.Column("detected_index", sa.Integer(), nullable=True),
        sa.Column("detected_bool", sa.Boolean(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "outcome",
            postgresql.ENUM(
                "DETECTED",
                "LOW_CONFIDENCE",
                "BLANK",
                "MULTIPLE",
                "CORRECTED",
                "NOT_GRADEABLE",
                name="detection_outcome",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("fill_ratios", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("bubble_boxes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("corrected_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_detection"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_detection_school_id_school", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["corrected_by_id"],
            ["teacher.id"],
            name="fk_detection_corrected_by_id_teacher",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sheet_item_id"],
            ["sheet_item.id"],
            name="fk_detection_sheet_item_id_sheet_item",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_page_id"],
            ["scan_page.id"],
            name="fk_detection_scan_page_id_scan_page",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_detection_scan_page_id", "detection", ["scan_page_id"])
    op.create_index("ix_detection_school_id", "detection", ["school_id"])
    op.create_index("ix_detection_sheet_item_id", "detection", ["sheet_item_id"])
    op.create_index("ix_detection_corrected_by_id", "detection", ["corrected_by_id"])

    op.create_table(
        "attempt",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exercise_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sheet_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sheet_instance_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("detection_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_attempt"),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detection.id"],
            name="fk_attempt_detection_id_detection",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["student.id"], name="fk_attempt_student_id_student", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
            name="fk_attempt_exercise_id_exercise",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["sheet.id"], name="fk_attempt_sheet_id_sheet", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["sheet_instance_id"],
            ["sheet_instance.id"],
            name="fk_attempt_sheet_instance_id_sheet_instance",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_attempt_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_attempt_exercise_id", "attempt", ["exercise_id"])
    op.create_index("ix_attempt_sheet_id", "attempt", ["sheet_id"])
    op.create_index("ix_attempt_school_id", "attempt", ["school_id"])
    op.create_index("ix_attempt_student_id", "attempt", ["student_id"])
    op.create_index("ix_attempt_sheet_instance_id", "attempt", ["sheet_instance_id"])
    op.create_index("ix_attempt_detection_id", "attempt", ["detection_id"])
    op.create_index("ix_attempt_student_answered", "attempt", ["student_id", "answered_at"])

    op.create_table(
        "mastery_snapshot",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("competency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "band",
            postgresql.ENUM(
                "SOLID", "OK", "WEAK", "FADING", "NONE", name="mastery_band", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("attempts_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_mastery_snapshot"),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name="fk_mastery_snapshot_school_id_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_mastery_snapshot_student_id_student",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competency.id"],
            name="fk_mastery_snapshot_competency_id_competency",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1", name="ck_mastery_snapshot_score_unit_interval"
        ),
    )
    op.create_index("ix_mastery_snapshot_competency_id", "mastery_snapshot", ["competency_id"])
    op.create_index("ix_mastery_snapshot_school_id", "mastery_snapshot", ["school_id"])
    op.create_index("ix_mastery_snapshot_student_id", "mastery_snapshot", ["student_id"])
    op.create_index(
        "ix_mastery_student_competency",
        "mastery_snapshot",
        ["student_id", "competency_id", "computed_at"],
    )

    op.create_table(
        "model_call",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("purpose", sa.String(length=60), nullable=False),
        sa.Column("prompt_name", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("prompt_sha256", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_estimate_chf", sa.Float(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_model_call"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_model_call_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_model_call_school_id", "model_call", ["school_id"])

    op.create_table(
        "job",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "INGEST_SOURCE",
                "RENDER_SHEET",
                "PROCESS_SCAN",
                "GENERATE_ADAPTIVE",
                name="job_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED", "RUNNING", "SUCCEEDED", "FAILED", name="job_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("school_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_job"),
        sa.ForeignKeyConstraint(
            ["school_id"], ["school.id"], name="fk_job_school_id_school", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_job_school_id", "job", ["school_id"])


def downgrade() -> None:
    for table_name in _TABLE_DROP_ORDER:
        op.drop_table(table_name)

    for name in reversed(list(_ENUMS)):
        op.execute(f"DROP TYPE {name}")

    # The vector extension is left in place: it is cluster-wide, cheap to
    # keep, and other schemas/tenants in the same database could depend on
    # it. Drop it manually if this is truly the last consumer.
